<div class="alert alert-block alert-success">
    <h1 align="center">Machine Learning in Python</h1>
    <h3 align="center">Data PreProcessing</h3>
</div>

<img src="https://miro.medium.com/max/875/0*1-i9w0e4kklVQl5B.jpg" width=75% />

<img src="https://www.kdnuggets.com/wp-content/uploads/text-data-task-framework-preprocessing.png" width=75% />

# Topics:

- [ ] Importing the libraries
- [ ] Importing the dataset
- [ ] Missing values
- [ ] Encoding categorical data
- - [ ] Encoding the Independent Variable
- - [ ] Encoding the Dependent Variable
- [ ] Splitting the dataset into the Training set and Test set
- [ ] Feature Scaling

<img src="https://i.morioh.com/fcc4a5d877.png" width=50% />

# Importing Libraries

In [2]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

ModuleNotFoundError: No module named 'matplotlib'

# importing Dataset 

## (Solution 1)

In [ ]:
df = pd.read_csv('Data3.csv')

In [ ]:
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [ ]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [ ]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [ ]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## (Solution 2)


In [ ]:
df.columns

Index(['Country', 'Age', 'Salary', 'Purchased'], dtype='object')

In [ ]:
X = df[['Country', 'Age', 'Salary']].values
y = df ['Purchased'].values

In [ ]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [ ]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

# Missing Values

<img src="https://machinelearningmastery.com/wp-content/uploads/2017/03/How-to-Handle-Missing-Values-with-Python.jpg" width=50% />

### Sources of Missing Values

Before we dive into code, it’s important to understand the sources of missing data. Here’s some typical reasons why data is missing:

* User forgot to fill in a field.
* Data was lost while transferring manually from a legacy database.
* There was a programming error.
* Users chose not to fill out a field tied to their beliefs about how the results would be used or interpreted.

In [ ]:
df.isnull().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

## (Solution 1) Dropna

In [ ]:
df_dropna = df.copy()

In [ ]:
# summarize the shape of the raw data
print("Before:",df_dropna.shape)

# drop rows with missing values
df_dropna.dropna(inplace=True)

# summarize the shape of the data with missing rows removed
print("After:",df_dropna.shape)

Before: (10, 4)
After: (8, 4)


## (Solution 2) Use Fillna

In [ ]:
df_fillna = df.copy()

In [ ]:
df_fillna

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [ ]:
# fill missing values with mean column values
df_fillna.fillna(df_fillna.median(), inplace=True)
# count the number of NaN values in each column
print(df_fillna.isnull().sum())

df_fillna

Country      0
Age          0
Salary       0
Purchased    0
dtype: int64


<ipython-input-15-b4dd39c44219>:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df_fillna.fillna(df_fillna.median(), inplace=True)


Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0  61000.0       Yes
5   France  35.0  58000.0       Yes
6    Spain  38.0  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

## (Solution 3) Use Scikit-learn

The scikit-learn library provides the SimpleImputer pre-processing class that can be used to replace missing values.

It is a flexible class that allows you to specify the value to replace (it can be something other than NaN) and the technique used to replace it (such as mean, median, or mode). The SimpleImputer class operates directly on the NumPy array instead of the DataFrame.

<img src="https://images.g2crowd.com/uploads/product/image/large_detail/large_detail_77c883b19775c25838d2055fc2e7387e/scikit-learn.png" width=35% />

In [ ]:
df = pd.read_csv('Data3.csv')
X = df.iloc[:, :-1].values
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='median')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

# imputer.fit_transform(X[:,1:3])

In [ ]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 61000.0]
 ['France' 35.0 58000.0]
 ['Spain' 38.0 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


# Encoding the Independent Variable

In [ ]:
df['Country'].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 61000.0]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.0 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


# Encoding the Dependent Variable

-----------------------------------
### Ex1: How to replace No:0 and Yes:1 in y ?
-----------------------------------

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


#  Splitting the dataset into the Training set and Test set

<img src="https://files.realpython.com/media/Splitting-Datasets-With-sklearns-train_test_split_Watermarked.e321471660be.jpg" width=75% />

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state= 26)

In [ ]:
print(X_train)

[[1.0 0.0 0.0 37.0 67000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 52000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [ ]:
print(X_test)

[[0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 40.0 61000.0]]


In [ ]:
print(y_train)

[1 1 0 0 1 0 0 1]


In [ ]:
print(y_test)

[0 1]


# Feature Scaling

Feature Scaling or Standardization: It is a step of Data Pre Processing which is applied to independent variables or features of data. It basically helps to normalise the data within a particular range. Sometimes, it also helps in speeding up the calculations in an algorithm.

<img src="https://miro.medium.com/max/2000/1*yR54MSI1jjnf2QeGtt57PA.png" width=50% />

1) Min Max Scaler (Normalization)

2) Standard Scaler


<img src="https://cdn.analyticsvidhya.com/wp-content/uploads/2020/04/Feature-image-Normalization-vs.-Standardization.png" width=70% />

Another reason why feature scaling is applied is that few algorithms like gradient descent converge much faster with feature scaling than without it.

<img src="https://miro.medium.com/max/750/1*yi0VULDJmBfb1NaEikEciA.png" width=50% />

<img src="https://miro.medium.com/max/1400/1*_783tuRRVcTUwyFWB8VG0g.png" width=60% />

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [ ]:
print(X_train)

[[1.0 0.0 0.0 -0.01961538606622683 0.5668117703926832]
 [1.0 0.0 0.0 1.7065385877617345 1.7760102138970737]
 [0.0 1.0 0.0 -1.1180770057749294 -0.7431532100704068]
 [0.0 0.0 1.0 0.13730770246358784 -0.037787451359512204]
 [0.0 0.0 1.0 -1.5888462713643734 -1.3477524318226022]
 [1.0 0.0 0.0 1.0788462336424758 1.0706444551861791]
 [0.0 0.0 1.0 0.13730770246358784 -0.9446862839878052]
 [1.0 0.0 0.0 -0.3334615631258562 -0.34008706223560986]]


In [ ]:
print(X_test)

[[0.0 1.0 0.0 2.020384764821364 2.1790763617318705]
 [0.0 1.0 0.0 0.45115387952321717 -0.037787451359512204]]


## When to use feature Scaling ...

1. Gradient Descent:

Machine learning algorithms like linear regression, logistic regression, neural network, etc. that use gradient descent as an optimization technique require data to be scaled. Take a look at the formula for gradient descent below:

<img src="https://cdn.analyticsvidhya.com/wp-content/uploads/2020/03/gradient-descent.png" width=35% />

The presence of feature value X in the formula will affect the step size of the gradient descent. The difference in ranges of features will cause different step sizes for each feature. To ensure that the gradient descent moves smoothly towards the minima and that the steps for gradient descent are updated at the same rate for all the features, we scale the data before feeding it to the model.

> Having features on a similar scale can help the gradient descent converge more quickly towards the minima.

2. Distance-Based Algorithms:

Distance algorithms like KNN, K-means, and SVM are most affected by the range of features. This is because behind the scenes they are using distances between data points to determine their similarity.

Since both the features have different scales, there is a chance that higher weightage is given to features with higher magnitude. This will impact the performance of the machine learning algorithm and obviously, we do not want our algorithm to be biassed towards one feature.

> Therefore, we scale our data before employing a distance based algorithm so that all the features contribute equally to the result.

3. Tree-Based Algorithms: 

Tree-based algorithms, on the other hand, are fairly insensitive to the scale of the features. Think about it, a decision tree is only splitting a node based on a single feature. The decision tree splits a node on a feature that increases the homogeneity of the node. This split on a feature is not influenced by other features.

So, there is virtually no effect of the remaining features on the split. This is what makes them invariant to the scale of the features!

<img src="https://www.analyticsvidhya.com/wp-content/uploads/2015/01/Decision_Tree_2.png" width=40% />

### What is Normalization?

Normalization is a scaling technique in which values are shifted and rescaled so that they end up ranging between 0 and 1. It is also known as Min-Max scaling.

<img src="https://cdn.wallstreetmojo.com/wp-content/uploads/2019/04/Normalization-Formula.jpg" width=50% />

### What is Standardization?

Standardization is another scaling technique where the values are centered around the mean with a unit standard deviation. This means that the mean of the attribute becomes zero and the resultant distribution has a unit standard deviation.

In [ ]:
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])
print(X_train)


ModuleNotFoundError: No module named 'sklearn'

<img src="https://media-exp1.licdn.com/dms/image/C4E12AQHWVhZuYvqN-w/article-inline_image-shrink_1000_1488/0/1611663248964?e=1625702400&v=beta&t=AwmVMFx_ryMKzIchkyb9Kjpg49Oz1KxxwWdjfQp35s8" width=70% />